{% set name = "openjdk" %}
{% set version = "8.0.282" %}
{% set zulu_build = "8.52.0.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-ca-jdk{{ version }}-linux_x64.tar.gz  # [linux64]
    sha256: 36c39878724f509d765a8f3804f6cef87c2eff39ac85447a0dc870231c1d3bca  # [linux64]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-ca-jdk{{ version }}-macosx_x64.zip  # [osx and not arm64]
    sha256: a2f161b41dc8e812e223645dbbf8f57fc1224006aab9243d1b1d7f2502c95f11  # [osx and not arm64]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-ca-jdk{{ version }}-macosx_aarch64.tar.gz  # [osx and arm64]
    sha256: 011845318d37567ff2cb63d0f9115dd251504dc0d9156c9b7d9c4213a032c3be  # [osx and arm64]

  - url: https://cdn.azul.com/zulu/bin/zulu{{ zulu_build }}-ca-jdk{{ version }}-win_x64.zip  # [win64]
    sha256: af76e1a483ec7a119716e4b9c2f4c050ce413b5b15afe66563f25048a1b00220  # [win64]

  - url: https://cdn.azul.com/zulu-embedded/bin/zulu{{ zulu_build }}-ca-jdk{{ version }}-linux_aarch64.tar.gz  # [aarch64]
    sha256: ae0ad6046f6e7e751b43c615e3d37afc8b6b1c19b88dffd5f22c225aae9d26a7  # [aarch64]

  - url: https://github.com/dejavu-fonts/dejavu-fonts/releases/download/version_2_37/dejavu-fonts-ttf-2.37.zip  # [linux64]
    sha256: 7576310b219e04159d35ff61dd4a4ec4cdba4f35c00e002a136f00e96a908b0a  # [linux64]
    folder: fonts  # [linux64]

build:
  number: 0

test:
  requires:
    - {{ compiler('c') }}  # [not win]
  files:
    - test-jni  # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version  # [not (build_platform != target_platform and target_platfrom == "osx-arm64")]
    - ./test-jni.sh  # [not (win or (build_platform != target_platform and target_platfrom == "osx-arm64"))]

about:
  home: https://www.azul.com/products/zulu/
  license: GPL-2.0-or-later WITH Classpath-exception-2.0
  license_file: LICENSE
  summary: The Zulu OpenJDK build.
  description: Zulu OpenJDK is an open source build of the Java JDK.

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
    - hadim
    - CJ-Wright
    - xhochy
    - roccqqck
