travis:
  secure:
    BINSTAR_TOKEN: SCOhDagd738x7vnuI+wAgukZS4p054LiiaDYLTF58be3BMSQnxMF2JwOlHcq3DMKoBR8Wei/eSfnONu7OzmcadEcqOflnH9qwWWxrlCKnbNZOQm2Lc6/9VSkjbF3vSJd6+B057jO758vpUj+hkYKum9PatQEkaG7sD6pWdTG2+nw6Dw6QO3Am5W/+8VNucIohh1HLIUYJCH7Qanm5ssM19Xsa8ADuQjCIH/jrd3B9FLPwPDByHlJKlpHiCXWaJcn3eeS6UQoCXn44M+Z4fKLU7jskyP6Xn4oufFvYf7FCoLTufL/O5UW0Rc1SGe9DOSERWRDdyt2C8pQvCJsfWU43AeQvUUToq1S1Rm/V5g1jte0G1OdXkoUdwsCipcWIu+P7YSiTZEd8a//SWnCSHu31NMvv7D/6H8JLC3FGJc+PTHjBG+/MP3nJRFwz4uxmiIM/w5ZH+J6lOSMl06LbGkwm/xaVJsvXenFViYPkWPwJCqIkUR3PutHIndzXSAYZMa3M8CgI9tMjezK58Q6OjzDWG/XAnssgjYy0qpt/R5jbChDKFxq0fZ3swz77QRp+nzZ6YcYuXrQsVZL1LZPb1U8CJnfVZyqKBBYtAIzC95EQw7zo4vFWEfLDupXj1C+2G5Fil21FdNa89lGzUzPDc+EH09Zqj2++AabmUj9PCLTbkI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
